version: '3'

services:
  roadmap:
    build:
      context: ""
      dockerfile: ./docker/Dockerfile
    container_name: roadmap
    tty: true
    environment:
      SERVICE_NAME: roadmap
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - app-data:/var/www
      - php-config:/usr/local/etc/php/conf.d
    networks:
      - roadmap

  roadmap-webserver:
    image: nginx:alpine
    container_name: roadmap-webserver
    tty: true
    ports:
      - "1337:81"
      - "5577:443"
    volumes:
      - app-data:/var/www
      - nginx-config:/etc/nginx/conf.d
    networks:
      - roadmap
    depends_on:
      - roadmap

  roadmap-db:
    image: mysql:5.7.22
    container_name: roadmap-db
    restart: unless-stopped
    tty: true
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: roadmap
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: roadmap-mysql
    volumes:
      - db-data:/var/lib/mysql
      - mysql-init:/docker-entrypoint-initdb.d
      - mysql-config:/etc/mysql
    networks:
      - roadmap

  roadmap-myadmin:
    image: phpmyadmin
    container_name: roadmap-myadmin
    restart: always
    ports:
      - 8010:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - roadmap

networks:
  roadmap:
    driver: bridge

volumes:
  app-data:
  php-config:
  nginx-config:
  db-data:
  mysql-init:
  mysql-config:
